# Creating a logistic regression to predict absenteeism 

### by Mostafa Mahmoud

## Import the relevant libraries

In [1]:
import pandas as pd
import numpy as np

## Load the data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

## Create the targets

Logistic regression is a type of classification. So I will be claasifying people into two classes. Then preprocess the data to reflect this decision.

Classes are:
1. Moderately absent
2. Excessively absent

I will take the median value of the 'Absenteeism Time in Hours' and use it as a cut-off line. Reading below the median will be normal, and above the median will be excessive.

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
# Absent upto 3 hours will be assigned the value of 0, otherwise will be assigned the value of 1.
# In supervised ML, we call these 0s and 1s: TARGETS
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] >
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

- Using the median as a cut-off line is 'numerically stable and rigid'. As by using the median I have implicity balanced the dataset. This will prevent the model from learning to output only 0s or only 1s.

In [9]:
targets.sum() / targets.shape[0]

0.45571428571428574

- Around 46% of the targets are 1s
- Around 54% of the targets are 0s

A 60-40 split will usually work equally well for a logistic regression. But this isn't true for other algorithms.

In [10]:
# Drop 'Absenteeism Time in Hours' column
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the week', 
                                           'Daily Work Load Average', 'Distance to Work'], axis = 1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0         0         0         0         1                     289   33   
1         0         0         0         0                     118   50   
2         0         0         0         1                     179   38   
3         1         0         0         0                     279   39   
4         0         0         0         1                     289   33   

   Body Mass Index  Education  Children  Pets  Month Value  \
0               30          0         2     1            7   
1               31          0         1     0            7   
2               31          0         0     0            7   
3               24          0         2     0            7   
4               30          0         2     1            7   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## Select the Inputs for the regression

In [13]:
data_with_targets.shape

(700, 12)

In [14]:
# Select all rows and columns except 'Excessive Absenteeism'
data_with_targets.iloc[:, :14]

# Or data_with_targets.iloc[:, :-1]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         0         1                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month Value  \
0                 30          0         2     1            7   
1                 31          0         1     0            7   
2                 31          0         0     0            7   
3                 24          0         2     0            7   
4                 30          0         2     1            7   
..               ...        ...       ...   ...          ...   
695               22          1         2     0            5   
696               24          0         1     2            5   
697               25          1         0     0            5   
698               25          1         0     0            5   
699               25          0         1     1            5   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [15]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

In [16]:
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         0         1                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month Value  
0                 30          0         2     1            7  
1                 31          0         1     0            7  
2                 31          0         0     0            7  
3                 24          0         2     0            7  
4                 30          0         2     1            7  
..               ...        ...       ...   ...          ...  
695               22          1         2     0            5  
696               24          0         1     2            5  
697               25          1         0     0            5  
698               25          1         0     0            5  
699               25          0         1     1            5  

[700 rows x 11 columns]

## Standardize the data

In [17]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

- absenteeism_scaler will be used to subtract the mean and divide by the standard deviation variablewise (featurewise).

In [18]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    # Modified by me
    # def __init__(self,columns,copy=True,with_mean=True,with_std=True):
    def __init__(self,columns):
        
        # scaler is nothing but a Standard Scaler object
        
        # Modified by me
        #self.scaler = StandardScaler(copy,with_mean,with_std)
        self.scaler = StandardScaler()
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]
    

In [19]:
# check what are all columns that we've got
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value'], dtype=object)

In [20]:
# choose the columns to scale
# we later augmented this code and put it in comments
# columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']
    
# select the columns to omit
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [21]:
# create the columns to scale, based on the columns to omit
# use list comprehension to iterate over the list
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]
columns_to_scale

['Transportation Expense',
 'Age',
 'Body Mass Index',
 'Children',
 'Pets',
 'Month Value']

In [22]:
# declare a scaler object, specifying the columns you want to scale
absenteeism_scaler = CustomScaler(columns_to_scale)
absenteeism_scaler

CustomScaler(columns=['Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets', 'Month Value'])

In [23]:
# Calculate the mean and the standard deviation for each feature from unscaled_inputs
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets', 'Month Value'])

In [24]:
# I have prepared the 'scaling mechanism', and now I will apply it using the transform() method
# Here, we subtract the mean and divide by the standard deviation
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

Whenever we get new data, we will just apply absenteeism_scaler.transform(new_data_raw) to reach the same transformation as we did. Tis is the most and common and useful way to transform new data when you deploy a model.

new_data_raw = pd.read_csv('new_data.csv')

new_data_scaled = absenteeism_scaler.transform(new_data_raw)

In [25]:
# All input data has beeen standardized
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
0           0         0         0         1                1.005844 -0.536062   
1           0         0         0         0               -1.574681  2.130803   
2           0         0         0         1               -0.654143  0.248310   
3           1         0         0         0                0.854936  0.405184   
4           0         0         0         1                1.005844 -0.536062   
..        ...       ...       ...       ...                     ...       ...   
695         1         0         0         0               -0.654143  0.562059   
696         1         0         0         0                0.040034 -1.320435   
697         1         0         0         0                1.624567 -1.320435   
698         0         0         0         1                0.190942 -0.692937   
699         0         0         0         1                1.036026  0.562059   

     Body Mass Index  Education  Children      Pets  Month Value  
0           0.767431          0  0.880469  0.268487     0.182726  
1           1.002633          0 -0.019280 -0.589690     0.182726  
2           1.002633          0 -0.919030 -0.589690     0.182726  
3          -0.643782          0  0.880469 -0.589690     0.182726  
4           0.767431          0  0.880469  0.268487     0.182726  
..               ...        ...       ...       ...          ...  
695        -1.114186          1  0.880469 -0.589690    -0.388293  
696        -0.643782          0 -0.019280  1.126663    -0.388293  
697        -0.408580          1 -0.919030 -0.589690    -0.388293  
698        -0.408580          1 -0.919030 -0.589690    -0.388293  
699        -0.408580          0 -0.019280  0.268487    -0.388293  

[700 rows x 11 columns]

In [26]:
scaled_inputs.shape

(700, 11)

## Split the data into train & test and shuffle
- train is the data used in supervised learning after moving a small part for testing the model.
- test is a small part of data that will be used to test the model.
- shuffle is mixing the data in random order

## Import the relevant module

In [27]:
from sklearn.model_selection import train_test_split

## Split

In [28]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
 42          0         0         0         1               -0.654143  0.248310   
 404         1         0         0         0               -1.574681  2.130803   
 535         0         0         0         1               -0.654143  0.248310   
 47          0         0         0         1                1.036026  0.562059   
 229         1         0         0         0                0.190942  0.091435   
 ..        ...       ...       ...       ...                     ...       ...   
 563         0         0         0         1                0.190942  1.032682   
 483         0         0         0         1               -1.574681  0.091435   
 101         0         0         0         1                0.190942  0.091435   
 684         0         0         0         1               -0.654143 -1.006686   
 595         0         0         0         1               -0.654143  0.248310   
 
      Body Mas

- array 1: a training dataset with inputs
- array 2: a training dataset with targets
- array 3: a test dataset with inputs
- array 4: a test dataset with targets

In [29]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets)

In [30]:
print(x_train.shape, y_train.shape)      # 75% for training

(525, 11) (525,)


In [31]:
print(x_test.shape, y_test.shape)       # 25% for testing

(175, 11) (175,)


- Usually, we opt for splits like 90-10 or 80-20 (because we want to train on more data)
- We can set that by specifying a value for train_size (between 0 and 1):

x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8)

0.9 means 80% for training, and 20% for testing.

- shuffle splits arrays or matrices into random train and test subsets, by default shuffle is set to True.

sklearn.mode_selection.train_test_split(inputs, targets, train_size, shuffle=True)

- When we rerun our code we get a different split every time because of shuffle.
- We can set a value for random_state, to make shuffle works each time in the same random way.

sklearn.mode_selection.train_test_split(inputs, targets, train_size, shuffle=True, random_state = 20)


In [32]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [33]:
print(x_train.shape, y_train.shape)      # 80% for training

(560, 11) (560,)


In [34]:
print(x_test.shape, y_test.shape)       # 20% for testing

(140, 11) (140,)


## Training and Evaluating the Model
- Machine learning is 90% preprocessing and 10% modeling.

## Logistic regression with sklearn

In [35]:
# from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# Modified by me
import sklearn.linear_model as lm

## Training the model

In [36]:
# Declare a new variable to be a logistic regression object
# reg = LogisticRegression()

# Modified by me
reg = lm.LogisticRegression()

In [37]:
# fit the logistic regression model
# fits the model according to the given training data
reg.fit(x_train, y_train)

LogisticRegression()

In [38]:
# Evaluate the model accuracy
# Returns the mean accuracy on the given test data and labels
reg.score(x_train, y_train)

0.7732142857142857

### Manually check the accuracy
- To have a full understanding of what we are doing.
- As we will be using this idea later on.

To find the accuracy of a model manually, we should compare the model outputs with the targets.

In [39]:
# To find the model output I will use the predict() method
model_outputs = reg.predict(x_train)

In [40]:
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [41]:
# To display the targets
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [42]:
# To compare model outputs with targets
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [43]:
# To get the total number of True entries
np.sum((model_outputs==y_train))

433

In [44]:
model_outputs.shape[0]

560

In [45]:
# To get the accuracy
# Accuracy = Correct predictions / observations
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7732142857142857

- The same result as reg.score(x_train, y_train)

### Finding the intercept and coefficients

In [46]:
reg.intercept_

array([-1.6474549])

In [47]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.60528415,
        -0.16989096,  0.27981088, -0.21053312,  0.34826214, -0.27739602,
         0.1589299 ]])

- Whenever we employ sklearn (usually) the results are arrays, not data frames

In [48]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value'], dtype=object)

In [49]:
feature_name = unscaled_inputs.columns.values

In [50]:
# Create dataframe that contains the intercept, the feature_name. and the corresponding coefficients
summary_table = pd.DataFrame(columns=['feature name'], data = feature_name)

# Match the columns names with the coefficients
summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

feature name  Coefficient
0                 Reason_1     2.800197
1                 Reason_2     0.951884
2                 Reason_3     3.115553
3                 Reason_4     0.839001
4   Transportation Expense     0.605284
5                      Age    -0.169891
6          Body Mass Index     0.279811
7                Education    -0.210533
8                 Children     0.348262
9                     Pets    -0.277396
10             Month Value     0.158930

In [51]:
# Add the intercept
# first I will shift up all indicies by 1 so index 0 will be empty
# then we can fill it with the intercept value
summary_table.index = summary_table.index + 1
summary_table

feature name  Coefficient
1                 Reason_1     2.800197
2                 Reason_2     0.951884
3                 Reason_3     3.115553
4                 Reason_4     0.839001
5   Transportation Expense     0.605284
6                      Age    -0.169891
7          Body Mass Index     0.279811
8                Education    -0.210533
9                 Children     0.348262
10                    Pets    -0.277396
11             Month Value     0.158930

In [52]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table

feature name  Coefficient
1                 Reason_1     2.800197
2                 Reason_2     0.951884
3                 Reason_3     3.115553
4                 Reason_4     0.839001
5   Transportation Expense     0.605284
6                      Age    -0.169891
7          Body Mass Index     0.279811
8                Education    -0.210533
9                 Children     0.348262
10                    Pets    -0.277396
11             Month Value     0.158930
0                Intercept    -1.647455

In [53]:
summary_table = summary_table.sort_index()
summary_table

feature name  Coefficient
0                Intercept    -1.647455
1                 Reason_1     2.800197
2                 Reason_2     0.951884
3                 Reason_3     3.115553
4                 Reason_4     0.839001
5   Transportation Expense     0.605284
6                      Age    -0.169891
7          Body Mass Index     0.279811
8                Education    -0.210533
9                 Children     0.348262
10                    Pets    -0.277396
11             Month Value     0.158930

### Interpreting the Coefficients
- coefficient is also called weight.
- intercept is also called bias.
- The closer the coefficient to 0, the smaller the weight.
- The far the coefficient from 0 no matter it is positive or negative, the bigger the weight.
- Standardized coefficients are the coefficients of a regression where all variables have been standardized. They allow for simple and easy understand for comparison between the variables.
- Whichever weight is bigger, its corresponding featurte is more important.

In [54]:
# Get the exponentials of the coefficients
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [55]:
summary_table

feature name  Coefficient  Odds_ratio
0                Intercept    -1.647455    0.192539
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
3                 Reason_3     3.115553   22.545903
4                 Reason_4     0.839001    2.314054
5   Transportation Expense     0.605284    1.831773
6                      Age    -0.169891    0.843757
7          Body Mass Index     0.279811    1.322880
8                Education    -0.210533    0.810152
9                 Children     0.348262    1.416604
10                    Pets    -0.277396    0.757754
11             Month Value     0.158930    1.172256

In [56]:
summary_table.sort_values('Odds_ratio', ascending=False)

feature name  Coefficient  Odds_ratio
3                 Reason_3     3.115553   22.545903
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
4                 Reason_4     0.839001    2.314054
5   Transportation Expense     0.605284    1.831773
9                 Children     0.348262    1.416604
7          Body Mass Index     0.279811    1.322880
11             Month Value     0.158930    1.172256
6                      Age    -0.169891    0.843757
8                Education    -0.210533    0.810152
10                    Pets    -0.277396    0.757754
0                Intercept    -1.647455    0.192539

- Most important up, least important down.

### Creating a Custom Scaler to Standardize Only Numerical Features
- To fix standardizing done to the dummy variables, by choosing only the columns we want to standardize.
- We should avoid these step by standardizing before creating dummies.

In [57]:
### Testing the model

In [58]:
reg.score(x_test, y_test)

0.75

- Based on the data that the model has never seen before, in 73.6% of the cases, the model will predict [correctly] if the person is going to be excessively absent.
- By definition, the test accuracy is always less than the train accuracy. If we get a higher number, we may are lucky or made a mistake.
- Often the test accuracy is 10-20% lower than the train accuracy ( due to overfitting)

Overfitting means that our model learned the train data very well but it fails in real life.

In [59]:
# To get the probability of an output being 0 or 1 using predict_proba() method
# (instead of using the predict method to get the model output of 0 and 1)
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

- Left probability of 0
- Right probability of 1

Here, summing any two numbers horizontally will give output of 1.

In [60]:
predicted_proba.shape

(140, 2)

In [61]:
# Slicing all values from the second column (1) - Excessive Absenteeism
predicted_proba[:, 1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

- In reality, logistic regression models calculate these probabilities in the background.
- If the probability is below 0.5, it places a 0.
- If the probability is above 0.5, it places a 1.

### Saving the Logistic Regression Model
- Saving a model is the process of creating a file containing all the information regarding the machine learning.
- I will save the model using the pickle module.
- pickle module is a Python module used to convert a Python object into a character stream.
  ( Saving the reg variable to  a file).

In [62]:
import pickle

In [63]:
# filename is model, wb is write bytes, dump is save, load (instead of dump) is unpickle, reg is object to be dumped.
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [64]:
# We Must save the absenteeism_scaler, too!!
# We are basically separating the model from the training data  ... for good
# The information in the absenteeism_scaler is used to preprocess new data.
with open('scaler', 'wb') as file:
    pickle.dump(reg, file)

- The second step of the deployment is about creating a mechanism to load the saved model and make predictions
- We can use one of two approaches:
1. changing the .csv filename and fix issues.
2. creating a module and it is the prefered approach ( optimized version of the written code with functions)